spring:
  datasource:
    url: jdbc:mysql://localhost:3306/prod
    username: root
    password: root0000
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

details:
  env: Production environment
  version: 2.0
  author: srimanta-g
  contact:
    - srimanta@gmail.com
    - +918110054321
